# Generated by Django 3.0.8 on 2021-06-25 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='کلاس',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_class', models.IntegerField()),
                ('zarfit_class', models.IntegerField()),
                ('sakhteman_amozeshi', models.CharField(max_length=200)),
                ('description_class', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='گروه_اموزشی',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_groh', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('modir_groh', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('kardani', 'کاردانی'), ('karshenasi', 'کارشناسی'), ('kardani_and_karshenasi', 'کاردانی و کارشناسی')], default='kardani_and_karshenasi', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='درس',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_dars', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('count_vahed', models.IntegerField()),
                ('description_dars', models.TextField()),
                ('class_bargozari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.کلاس')),
                ('for_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.گروه_اموزشی')),
            ],
        ),
    ]
