# Generated by Django 3.0.8 on 2021-07-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20210701_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='درس',
            name='days',
            field=models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', ' یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه_شنبه', 'سه_شنبه'), ('چهارشنبه', 'چهارشنبه')], default='شنبه', max_length=100),
        ),
        migrations.AddField(
            model_name='درس',
            name='time_etmam',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='درس',
            name='time_shoro',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
